# Generated by Django 3.0.8 on 2020-08-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waist', models.CharField(max_length=100, verbose_name='Талия')),
                ('hips', models.CharField(max_length=100, verbose_name='Бёдра')),
                ('hand', models.CharField(max_length=100, verbose_name='Рука')),
                ('chest', models.CharField(max_length=100, verbose_name='Грудь')),
                ('height', models.CharField(max_length=100, verbose_name='Рост')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
            },
        ),
    ]
