# Generated by Django 3.0.8 on 2020-11-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(default='', max_length=100, verbose_name='Телефон')),
                ('email', models.CharField(default='', max_length=100, verbose_name='Email')),
                ('message', models.CharField(default='', max_length=800, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сообщения',
                'verbose_name_plural': 'Сообщение',
            },
        ),
    ]
